import RestaurantHeader from "../components/RestaurantHeader";

type RestaurantLayoutProps = {
    children: React.ReactNode;
}

export const metadata = {
    title: 'Menu of Milestone-Grill',
    description: 'Generated by create next app',
}

const RestaurantLayout = ({children}: RestaurantLayoutProps) => {
    return (
        <>
            <>
                {children}
            </>
        </>
    )
}

export default RestaurantLayout;