export const metadata = {
    title: 'Search Restaurant',
    description: 'Generated by create next app',
}

type SearchProps = {
    children: React.ReactNode
}

const SearchLayout = ({children} : SearchProps) => {
    return (
        <>
            {children}
        </>
    )
}

export default SearchLayout