import RestaurantHeader from "./components/RestaurantHeader";

type RestaurantLayoutProps = {
    children: React.ReactNode;
}

export const metadata = {
    title: 'Milestone-Grill',
    description: 'Generated by create next app',
}

const RestaurantLayout = ({children}: RestaurantLayoutProps) => {
    return (
        <>
            <RestaurantHeader/>
            <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
                {children}
            </div>
        </>
    )
}

export default RestaurantLayout;